# Generated by Django 5.2.15 on 2026-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffirmativeNSUApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('year_level', models.IntegerField(default=1)),
                ('school_id', models.CharField(blank=True, max_length=30)),
                ('is_nsu_staff', models.BooleanField(default=False)),
                ('is_nsu_dependent', models.BooleanField(default=False)),
                ('staff_name', models.CharField(blank=True, max_length=200)),
                ('staff_employee_id', models.CharField(blank=True, max_length=50)),
                ('relationship_to_staff', models.CharField(blank=True, max_length=50)),
                ('has_baccalaureate', models.BooleanField(default=False)),
                ('shs_gpa', models.FloatField(blank=True, null=True)),
                ('shs_certificate', models.FileField(blank=True, null=True, upload_to='affirmative/shs/')),
                ('suc_exam_score', models.FloatField(blank=True, null=True)),
                ('suc_exam_certificate', models.FileField(blank=True, null=True, upload_to='affirmative/suc/')),
                ('is_tes_beneficiary', models.BooleanField(default=False)),
                ('qualified_for', models.CharField(choices=[('Affirmative', 'Affirmative Action Scholarship'), ('Staff', 'NSU Staff Scholarship'), ('None', 'Not Qualified')], default='None', max_length=20)),
                ('status', models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Needs Revision', 'Needs Revision'), ('Draft', 'Draft')], default='Pending Validation', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
