# Generated by Django 4.2.29 on 2026-07-01 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_affirmativensuapplication_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipRollover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_type', models.CharField(max_length=20)),
                ('school_year', models.CharField(max_length=20)),
                ('scholar_count', models.IntegerField(default=0)),
                ('excel_file', models.FileField(upload_to='rollovers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rolled_over_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
