# Generated by Django 4.2.29 on 2026-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scholarshiprollover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('TDP', 'TDP'), ('DOST', 'DOST'), ('CHED', 'CHED'), ('CoScho', 'CoScho'), ('Sports', 'Sports'), ('Affirmative', 'Affirmative'), ('Staff', 'Staff'), ('GSIS', 'GSIS')], max_length=20),
        ),
    ]
