# Generated by Django 4.2.29 on 2026-07-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_scholarship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='gwa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
