# Generated by Django 6.0.6 on 2026-07-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_archiverecord_extra_data_alter_archiverecord_gwa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_of_grades', models.FileField(upload_to='renewals/academic/')),
                ('certificate_of_enrollment', models.FileField(upload_to='renewals/academic/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_renewals', to='api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_type', models.CharField(max_length=50)),
                ('proof_document', models.FileField(upload_to='link_requests/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to='api.studentprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='BillingRecord',
        ),
        migrations.DeleteModel(
            name='LiquidationRecord',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
