# Generated by Django 6.0.6 on 2026-07-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_unused_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiprollover',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], default='1st Semester', max_length=20),
        ),
    ]
