# Generated by Django 6.0.6 on 2026-07-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_semester_to_scholarshiprollover'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiprollover',
            name='label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
