# Generated by Django 6.0.6 on 2026-07-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_label_to_scholarshiprollover'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligibility_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
