# Generated by Django 6.0.6 on 2026-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_scholarship_background_scholarship_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='group',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('institutional', 'Institutional')], default='internal', max_length=20),
        ),
    ]
