# Generated by Django 6.0.6 on 2026-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_split_address_add_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='award_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='congress_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='rollover_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='student_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='scholar_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
