# Generated by Django 6.0.6 on 2026-08-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_archive_record_flat_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('complete_program', models.CharField(blank=True, max_length=200)),
                ('father_last_name', models.CharField(blank=True, max_length=100)),
                ('father_first_name', models.CharField(blank=True, max_length=100)),
                ('father_middle_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(blank=True, max_length=100)),
                ('mother_first_name', models.CharField(blank=True, max_length=100)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100)),
                ('street_barangay', models.CharField(blank=True, max_length=200)),
                ('city_municipality', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('disability_type', models.CharField(blank=True, max_length=100)),
                ('is_solo_parent_dependent', models.BooleanField(default=False)),
                ('is_first_gen_college', models.BooleanField(default=False)),
                ('indigenous_people_group', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tes_applications', to='api.studentprofile')),
            ],
        ),
    ]
