# Generated by Django 6.0.6 on 2026-08-22 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_staffrenewal_cog_coe'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_archive_records', to='api.studentprofile'),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='award_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='linked_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.application'),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='matched_archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_requests', to='api.archiverecord'),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_link_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='school_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshiplinkrequest',
            name='scholarship_type',
            field=models.CharField(choices=[('Academic', 'Academic Scholarship'), ('TDP', 'TDP Scholarship'), ('DOST', 'DOST Scholarship'), ('CHED', 'CHED Scholarship'), ('CoScho', 'CoScho Scholarship'), ('Sports', 'Sports Scholarship'), ('GSIS', 'GSIS Scholarship'), ('Affirmative', 'Affirmative Scholarship'), ('Staff', 'NSU Staff Scholarship')], max_length=50),
        ),
    ]
