# Generated by Django 6.0.6 on 2026-08-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_normalize_staff_scholarship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmativensuapplication',
            name='appointment_paper',
            field=models.FileField(blank=True, null=True, upload_to='staff/appointment/'),
        ),
        migrations.AddField(
            model_name='affirmativensuapplication',
            name='date_of_regularization',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affirmativensuapplication',
            name='designation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='affirmativensuapplication',
            name='employment_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='affirmativensuapplication',
            name='years_of_service',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
