# Generated by Django 6.0.6 on 2026-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_backfill_staff_details_from_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='affirmativensuapplication',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='affirmativensuapplication',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
