# Generated by Django 6.0.6 on 2026-08-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_clean_up_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmativensuapplication',
            name='designation',
            field=models.CharField(blank=True, choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], max_length=30),
        ),
        migrations.AlterField(
            model_name='affirmativensuapplication',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Contractual', 'Contractual'), ('Part-time', 'Part-time')], max_length=30),
        ),
    ]
