# Generated by Django 6.0.6 on 2026-08-23 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_middle_name_to_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='suffix',
            field=models.CharField(blank=True, help_text='Jr., Sr., III …', max_length=20),
        ),
        migrations.AlterField(
            model_name='affirmativensuapplication',
            name='qualified_for',
            field=models.CharField(choices=[('Affirmative', 'Affirmative Action Scholarship'), ('Staff', 'BiPSU Staff Scholarship'), ('None', 'Not Qualified')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshiplinkrequest',
            name='scholarship_type',
            field=models.CharField(choices=[('Academic', 'Academic Scholarship'), ('TDP', 'TDP Scholarship'), ('DOST', 'DOST Scholarship'), ('CHED', 'CHED Scholarship'), ('CoScho', 'CoScho Scholarship'), ('Sports', 'Sports Scholarship'), ('GSIS', 'GSIS Scholarship'), ('Affirmative', 'Affirmative Scholarship'), ('Staff', 'BiPSU Staff Scholarship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('nsu_staff', 'BiPSU Staff'), ('vpsea', 'VPSEA Admin'), ('unifast', 'UniFAST Admin'), ('super', 'Super Admin')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='Jr., Sr., III …', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(blank=True, db_index=True, help_text='School / employee ID, e.g. 32-1-213313', max_length=50)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('employment_status', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Contractual', 'Contractual'), ('Part-time', 'Part-time')], max_length=30)),
                ('designation', models.CharField(blank=True, choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], max_length=30)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('date_of_regularization', models.DateField(blank=True, null=True)),
                ('declared_years_of_service', models.IntegerField(blank=True, help_text='Only read when date_hired is blank — see the years_of_service property.', null=True)),
                ('appointment_paper', models.FileField(blank=True, null=True, upload_to='staff/appointment/')),
                ('highest_education', models.CharField(blank=True, max_length=200)),
                ('has_baccalaureate', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('separated_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'nsu_staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
