# Generated by Django 6.0.6 on 2026-08-24 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_fill_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Verified'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
