# Generated by Django 6.0.6 on 2026-08-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_account_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='citizenship',
            field=models.CharField(blank=True, help_text="Blank means not yet recorded, not 'non-Filipino'.", max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_previous_degree',
            field=models.BooleanField(blank=True, help_text='Holds an earlier undergraduate degree. Null means unknown.', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='household_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_4ps_beneficiary',
            field=models.BooleanField(blank=True, help_text='Pantawid Pamilyang Pilipino Program. Stands in for Listahanan when that list is unavailable.', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_listahanan_household',
            field=models.BooleanField(blank=True, help_text='DSWD Listahanan listing. Null means not yet checked against the list.', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_first_enrolled',
            field=models.IntegerField(blank=True, help_text='Calendar year the student first enrolled in this programme, for the maximum-years rule.', null=True),
        ),
    ]
