# Generated by Django 6.0.6 on 2026-08-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_parent_names_on_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmativensuapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='academic_year',
            field=models.CharField(default='26-1', help_text="Active term as '<yy>-<sem>', e.g. '26-1'. Must parse — see parse_label.", max_length=20),
        ),
    ]
