# Generated by Django 6.0.6 on 2026-08-25 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_affirmativensuapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='award_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='claimed_archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claiming_applications', to='api.archiverecord'),
        ),
        migrations.AddField(
            model_name='application',
            name='congress_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='school_year',
            field=models.CharField(blank=True, db_index=True, help_text="Expanded school year, e.g. '2026-2027'.", max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('portal', 'Student portal'), ('link', 'Approved link request'), ('tes_application', 'Approved TES application'), ('renewal', 'Approved renewal'), ('import', 'Office import')], db_index=True, default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='term_label',
            field=models.CharField(blank=True, db_index=True, help_text="Active term as '<yy>-<sem>', e.g. '26-1'.", max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='tes_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='api.tesapplication'),
        ),
        migrations.AlterField(
            model_name='application',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='application',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.scholarship'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['term_label', 'status'], name='api_applica_term_la_2ad527_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['scholarship', 'status'], name='api_applica_scholar_71162c_idx'),
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['scholarship_type', 'rollover_label', 'claimed_by'], name='api_archive_scholar_bcdf30_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student', 'is_read'], name='api_notific_student_153d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='tesapplication',
            index=models.Index(fields=['status'], name='api_tesappl_status_75ae3d_idx'),
        ),
    ]
