# Generated by Django 6.0.6 on 2026-08-26 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_entities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicrenewal',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='importedscholar',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scholarlistimport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tesapplication',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterField(
            model_name='affirmativestaffapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importedscholar',
            name='scholarship_type',
            field=models.CharField(choices=[('Academic', 'Academic Scholarship'), ('TDP', 'TDP Scholarship'), ('DOST', 'DOST Scholarship'), ('CHED', 'CHED Scholarship'), ('CoScho', 'CoScho Scholarship'), ('Sports', 'Sports Scholarship'), ('GSIS', 'GSIS Scholarship'), ('Affirmative', 'Affirmative Scholarship'), ('Staff', 'BiPSU Staff Scholarship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarlistimport',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholar_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scholarlistimport',
            name='scholarship_type',
            field=models.CharField(choices=[('Academic', 'Academic Scholarship'), ('TDP', 'TDP Scholarship'), ('DOST', 'DOST Scholarship'), ('CHED', 'CHED Scholarship'), ('CoScho', 'CoScho Scholarship'), ('Sports', 'Sports Scholarship'), ('GSIS', 'GSIS Scholarship'), ('Affirmative', 'Affirmative Scholarship'), ('Staff', 'BiPSU Staff Scholarship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='importedscholar',
            index=models.Index(fields=['scholarship_type', 'term_label', 'claimed_by'], name='api_importe_scholar_58d34e_idx'),
        ),
    ]
