# Generated by Django 6.0.6 on 2026-08-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_scholarshiplinkrequest_award_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='password',
        ),
    ]
