# Generated by Django 5.2.15 on 2026-08-29 06:20

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_affirmativestaffapplication_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrenewal',
            name='certificate_of_enrollment',
            field=models.FileField(upload_to='renewals/academic/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='academicrenewal',
            name='certificate_of_grades',
            field=models.FileField(upload_to='renewals/academic/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='affirmativestaffapplication',
            name='appointment_paper',
            field=models.FileField(blank=True, null=True, upload_to='staff/appointment/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='affirmativestaffapplication',
            name='shs_certificate',
            field=models.FileField(blank=True, null=True, upload_to='affirmative/shs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='affirmativestaffapplication',
            name='suc_exam_certificate',
            field=models.FileField(blank=True, null=True, upload_to='affirmative/suc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='scholarlistimport',
            name='excel_file',
            field=models.FileField(upload_to='rollovers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='scholarshiplinkrequest',
            name='proof_document',
            field=models.FileField(upload_to='link_requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='appointment_paper',
            field=models.FileField(blank=True, null=True, upload_to='staff/appointment/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='staffrenewal',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='renewals/staff/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='shs_gpa_cert',
            field=models.FileField(blank=True, null=True, upload_to='profile/shs_cert/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='suc_exam_cert',
            field=models.FileField(blank=True, null=True, upload_to='profile/suc_cert/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
    ]
