# Generated by Django 5.2.15 on 2026-08-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_staff_scholarship_group_internal'),
        ('api', '0046_upload_validators'),
    ]

    operations = [
    ]
