# Generated by Django 5.2.15 on 2026-08-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_merge_20260829_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmativestaffapplication',
            name='suc_exam_total',
            field=models.FloatField(blank=True, help_text='Items the exam was out of. Blank means the score is already a percentage.', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='suc_exam_total',
            field=models.FloatField(blank=True, help_text='Items the exam was out of. Blank means the score is already a percentage.', null=True),
        ),
        migrations.AlterField(
            model_name='affirmativestaffapplication',
            name='suc_exam_score',
            field=models.FloatField(blank=True, help_text='Raw score. A percentage when suc_exam_total is blank.', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='suc_exam_score',
            field=models.FloatField(blank=True, help_text='Raw score. A percentage when suc_exam_total is blank.', null=True),
        ),
    ]
