"""Let a scholarship choose the columns its archive table shows.

Additive only: an existing programme gets an empty selection, which
scholar_columns.resolve reads as "the default set" — the columns the archive
tables were hand-written with — so no table changes until someone picks.
"""
# Generated by Django 5.2.15 on 2026-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_drop_moved_studentprofile_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmativestaffapplication',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importedscholar',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='extra_columns',
            field=models.JSONField(blank=True, default=list, help_text="Columns the office added, as [{'key', 'label'}]."),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='table_columns',
            field=models.JSONField(blank=True, default=list, help_text='Column keys from api/scholar_columns.COLUMNS. Empty means the default set.'),
        ),
    ]
