"""Drop the Draft status, and move the rows that had it.

A draft was invisible to the office and unchaseable for the applicant. Anything
still sitting in one becomes a real submission — Pending Validation — so it
lands in the queue rather than disappearing when the choice stops existing.
"""
# Generated by Django 5.2.15 on 2026-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_scholarship_table_columns'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: [
                apps.get_model('api', name).objects
                .filter(status='Draft').update(status='Pending Validation')
                for name in ('Application', 'AffirmativeStaffApplication')
            ] and None,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='affirmativestaffapplication',
            name='status',
            field=models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Needs Revision', 'Needs Revision')], default='Pending Validation', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Needs Revision', 'Needs Revision')], default='Pending Validation', max_length=30),
        ),
    ]
