# Generated by Django 5.2.15 on 2026-09-03 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_tes_optional_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(db_index=True, help_text="Expanded school year, e.g. '2026-2027'.", max_length=20, unique=True)),
                ('tes_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Per grantee, per the CHED advice for this term.', max_digits=10, null=True)),
                ('tes_3a_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Top-up for a grantee with a disability. Decided per case.', max_digits=10, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=60)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tes_billing_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TES billing rate',
                'ordering': ['-school_year'],
            },
        ),
    ]
