"""Drop the columns 0058 copied onto the staff detail rows.

Reversible only as far as the schema goes: reversing recreates empty columns,
and 0058's reverse copies the values back into them.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_move_staff_records_onto_detail_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='appointment_paper',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='course',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='date_of_regularization',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='department',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='has_baccalaureate',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='is_nsu_dependent',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='is_nsu_staff',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='is_tes_beneficiary',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='position',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='relationship_to_staff',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='school',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='shs_certificate',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='shs_gpa',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='staff_employee_id',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='suc_exam_certificate',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='suc_exam_score',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='suc_exam_total',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='year_level',
        ),
        migrations.RemoveField(
            model_name='affirmativestaffapplication',
            name='years_of_service',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='appointment_paper',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='date_hired',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='date_of_regularization',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='declared_years_of_service',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='has_baccalaureate',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='highest_education',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='separated_on',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='suffix',
        ),
    ]
