"""Give a studying employee a course and year level.

The gap the 0057-0059 split turned up. StaffEmployment says where an employee
works and StaffEducation said only what they had already finished, so nothing on
the staff record said what they were currently enrolled in -- which is what the
masterlist prints for a staff scholar. Until now it could only be read off
whichever application the employee last submitted.

Added rather than moved: these are new columns, not columns from somewhere else.
"""
# Generated by Django 5.2.15 on 2026-09-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_drop_moved_staff_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffeducation',
            name='course',
            field=models.CharField(blank=True, help_text='The programme the employee is enrolled in as a scholar.', max_length=100),
        ),
        migrations.AddField(
            model_name='staffeducation',
            name='year_level',
            field=models.IntegerField(default=1),
        ),
    ]
