# Generated by Django 5.2.15 on 2026-09-05 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_drop_socioeconomic_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESLiquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(db_index=True, help_text="Expanded school year, e.g. '2026-2027'.", max_length=20, unique=True)),
                ('funds_received', models.DecimalField(blank=True, decimal_places=2, help_text='Total remitted by CHEDRO for this term, per the credit advice.', max_digits=12, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('credit_advice_no', models.CharField(blank=True, help_text='Credit advice, ADA or cheque reference the funds arrived under.', max_length=60)),
                ('report_no', models.CharField(blank=True, max_length=60)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tes_liquidation_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TES liquidation',
                'ordering': ['-school_year'],
            },
        ),
        migrations.CreateModel(
            name='TESDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_released', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('Unclaimed', 'Unclaimed'), ('Returned', 'Returned to CHED')], default='Unclaimed', max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=60)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tes_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='api.tesapplication')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tes_disbursement_updates', to=settings.AUTH_USER_MODEL)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='api.tesliquidation')),
            ],
            options={
                'ordering': ['tes_application__student__user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('liquidation', 'tes_application'), name='one_disbursement_per_grantee')],
            },
        ),
    ]
