# Generated by Django 5.2.15 on 2026-09-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_scholarship_types_from_the_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='logo',
            field=models.CharField(blank=True, help_text="Seal filename from media/logos/, e.g. 'CHED.png'. Blank uses the default for this programme type.", max_length=100),
        ),
    ]
