# Generated by Django 5.2.15 on 2026-09-06 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_tes_grantee_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesliquidation',
            name='approved_by',
            field=models.CharField(blank=True, help_text='University President.', max_length=120),
        ),
        migrations.AddField(
            model_name='tesliquidation',
            name='cashier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tesliquidation',
            name='certified_by',
            field=models.CharField(blank=True, help_text='Supervising Administrative Officer — Finance.', max_length=120),
        ),
        migrations.AddField(
            model_name='tesliquidation',
            name='prepared_by',
            field=models.CharField(blank=True, help_text='Designated TES/UniFAST focal person.', max_length=120),
        ),
        migrations.AddField(
            model_name='tesliquidation',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Audit team leader.', max_length=120),
        ),
        migrations.CreateModel(
            name='TESCheckIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('check_no', models.CharField(blank=True, help_text='Check No./ADA, as written on the TES-4 form.', max_length=60)),
                ('dv_or_no', models.CharField(blank=True, help_text='DV / Official Receipt number.', max_length=60)),
                ('responsibility_center_code', models.CharField(blank=True, max_length=60)),
                ('payee', models.CharField(blank=True, help_text='Usually the bank the payroll was credited through.', max_length=120)),
                ('nature_of_payment', models.TextField(blank=True, help_text='What the cheque paid for, as it should read on the form.')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='api.tesliquidation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tes_check_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TES check issued',
                'verbose_name_plural': 'TES checks issued',
                'ordering': ['date_issued', 'check_no', 'pk'],
            },
        ),
    ]
