# Generated by Django 5.2.15 on 2026-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_drop_tes_grantee_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesapplication',
            name='batch',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
