# Generated by Django 5.2.15 on 2026-09-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_partner_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTableColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_columns', models.JSONField(blank=True, default=list)),
                ('extra_columns', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns_set', to='api.partneroffice')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_columns', to='api.scholarship')),
            ],
            options={
                'verbose_name': 'partner table columns',
                'verbose_name_plural': 'partner table columns',
                'constraints': [models.UniqueConstraint(fields=('office', 'scholarship'), name='one_column_choice_per_partner_programme')],
            },
        ),
    ]
