# Generated by Django 5.2.15 on 2026-09-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_partner_table_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, help_text="Shown above the questions, in the partner's own words.")),
                ('is_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_forms', to='api.partneroffice')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_forms', to='api.scholarship')),
            ],
            options={
                'verbose_name': 'partner application form',
                'ordering': ['scholarship__name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('text', 'Short text'), ('textarea', 'Paragraph'), ('dropdown', 'Dropdown'), ('number', 'Number'), ('date', 'Date'), ('yesno', 'Yes / No')], default='text', max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.partnerapplicationform')),
            ],
            options={
                'verbose_name': 'partner form field',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PartnerFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_label', models.CharField(blank=True, db_index=True, help_text="Term as '<yy>-<sem>', e.g. '26-1'.", max_length=20)),
                ('school_year', models.CharField(blank=True, db_index=True, help_text="Expanded school year, e.g. '2026-2027'.", max_length=20)),
                ('semester', models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], max_length=20)),
                ('answers', models.JSONField(blank=True, default=list, help_text="[{'key', 'label', 'value'}] as the form read when answered.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.partnerapplicationform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_submissions', to='api.studentprofile')),
            ],
            options={
                'verbose_name': 'partner form submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='partnerapplicationform',
            constraint=models.UniqueConstraint(fields=('office', 'scholarship'), name='one_form_per_partner_programme'),
        ),
        migrations.AddConstraint(
            model_name='partnerformsubmission',
            constraint=models.UniqueConstraint(fields=('form', 'student', 'term_label'), name='one_partner_submission_per_term'),
        ),
    ]
