# Generated by Django 5.2.15 on 2026-09-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_affirmative_target_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedscholar',
            name='award_tier',
            field=models.CharField(blank=True, choices=[('Full', 'Full Merit / Full Scholar'), ('Half', 'Half Merit / Partial Scholar')], max_length=10),
        ),
    ]
