# Generated by Django 5.2.15 on 2026-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_imported_scholar_ched_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='filed_in_portal',
            field=models.BooleanField(default=False, help_text='Declared from the student portal rather than on the registration form.'),
        ),
    ]
