# Generated by Django 5.2.15 on 2026-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_registration_records_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SignupSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('kind', models.CharField(choices=[('alert', 'Scholarship alerts'), ('registration', 'Registration')], default='alert', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('utm_term', models.CharField(blank=True, max_length=120)),
                ('utm_content', models.CharField(blank=True, max_length=120)),
                ('referrer', models.CharField(blank=True, max_length=200)),
                ('landed_on', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'kind')},
            },
        ),
    ]
