# Generated by Django 5.2.15 on 2026-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_appointment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrenewal',
            name='scholarship_type',
            field=models.CharField(choices=[('Academic', 'Academic Scholarship'), ('TDP', 'TDP Scholarship'), ('SUC-TDP', 'SUC-TDP Scholarship'), ('TES', 'Tertiary Education Subsidy'), ('DOST', 'DOST S&T Undergraduate Scholarship'), ('JLSS', 'DOST Junior Level Science Scholarship'), ('CHED', 'CHED Scholarship'), ('CoScho', 'CoScho Scholarship'), ('Sports', 'Sports Scholarship'), ('GSIS', 'GSIS Scholarship'), ('Affirmative', 'Affirmative Scholarship'), ('Staff', 'BiPSU Staff Scholarship')], default='Academic', help_text='Which programme this submission renews.', max_length=50),
        ),
        migrations.AlterField(
            model_name='importedscholar',
            name='scholarship_type',
            field=models.CharField(choices=[('Academic', 'Academic Scholarship'), ('TDP', 'TDP Scholarship'), ('SUC-TDP', 'SUC-TDP Scholarship'), ('TES', 'Tertiary Education Subsidy'), ('DOST', 'DOST S&T Undergraduate Scholarship'), ('JLSS', 'DOST Junior Level Science Scholarship'), ('CHED', 'CHED Scholarship'), ('CoScho', 'CoScho Scholarship'), ('Sports', 'Sports Scholarship'), ('GSIS', 'GSIS Scholarship'), ('Affirmative', 'Affirmative Scholarship'), ('Staff', 'BiPSU Staff Scholarship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarlistimport',
            name='scholarship_type',
            field=models.CharField(choices=[('Academic', 'Academic Scholarship'), ('TDP', 'TDP Scholarship'), ('SUC-TDP', 'SUC-TDP Scholarship'), ('TES', 'Tertiary Education Subsidy'), ('DOST', 'DOST S&T Undergraduate Scholarship'), ('JLSS', 'DOST Junior Level Science Scholarship'), ('CHED', 'CHED Scholarship'), ('CoScho', 'CoScho Scholarship'), ('Sports', 'Sports Scholarship'), ('GSIS', 'GSIS Scholarship'), ('Affirmative', 'Affirmative Scholarship'), ('Staff', 'BiPSU Staff Scholarship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshiplinkrequest',
            name='scholarship_type',
            field=models.CharField(choices=[('Academic', 'Academic Scholarship'), ('TDP', 'TDP Scholarship'), ('SUC-TDP', 'SUC-TDP Scholarship'), ('TES', 'Tertiary Education Subsidy'), ('DOST', 'DOST S&T Undergraduate Scholarship'), ('JLSS', 'DOST Junior Level Science Scholarship'), ('CHED', 'CHED Scholarship'), ('CoScho', 'CoScho Scholarship'), ('Sports', 'Sports Scholarship'), ('GSIS', 'GSIS Scholarship'), ('Affirmative', 'Affirmative Scholarship'), ('Staff', 'BiPSU Staff Scholarship')], max_length=50),
        ),
    ]
