# Generated by Django 5.2.15 on 2026-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_tes_is_declarable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantrecord',
            name='qualified_for',
            field=models.CharField(choices=[('Affirmative', 'Affirmative Action Scholarship'), ('Staff', 'BiPSU Staff Scholarship'), ('None', 'Not Qualified')], db_index=True, default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantrecord',
            name='status',
            field=models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Needs Revision', 'Needs Revision')], db_index=True, default='Pending Validation', max_length=30),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarshiplinkrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=10),
        ),
        migrations.AddIndex(
            model_name='academicrenewal',
            index=models.Index(fields=['status', 'term_label'], name='api_academi_status_863567_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarlistimport',
            index=models.Index(fields=['scholarship_type', 'term_label'], name='api_scholar_scholar_a4b296_idx'),
        ),
    ]
