# Generated by Django 5.2.15 on 2026-09-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_optimization_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='linked_applicant_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.applicantrecord'),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='relationship_to_staff',
            field=models.CharField(blank=True, help_text='Staff Scholarship only: how the student is related to them.', max_length=50),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='staff_employee_id',
            field=models.CharField(blank=True, help_text="Staff Scholarship only: that employee's number.", max_length=50),
        ),
        migrations.AddField(
            model_name='scholarshiplinkrequest',
            name='staff_name',
            field=models.CharField(blank=True, help_text='Staff Scholarship only: the employee this student depends on.', max_length=200),
        ),
    ]
