# Generated by Django 5.2.15 on 2026-09-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_dependent_staff_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('import', 'Imported'), ('export', 'Exported'), ('sign-in', 'Signed in'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_type', 'target_id'], name='api_activit_target__debcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='api_activit_user_id_29f0f8_idx'),
        ),
    ]
