# Generated by Django 5.2.15 on 2026-09-20 07:41

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_activitylog_changes_activitylog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentdata',
            name='study_load',
            field=models.FileField(blank=True, help_text='Certificate of registration or study load for the current term. The office checks it to confirm the applicant is a bonafide, currently enrolled student — a student number alone survives a student leaving.', null=True, upload_to='profile/study_load/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'heic']), api.validators.MaxFileSize()]),
        ),
    ]
