# Generated by Django 5.2.15 on 2026-09-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_award_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Whether this account is asked for an authenticator code.'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_recovery_codes',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
