# Generated by Django 5.2.15 on 2026-09-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_backgroundjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_name',
            field=models.CharField(default='Student Development and Services Office', help_text='The office an SDSO account signs in on behalf of. Shown on its own profile and under its name in the sidebar.', max_length=120),
        ),
    ]
