# Generated by Django 5.2.15 on 2026-09-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_user_office_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='school_year',
            field=models.CharField(blank=True, db_index=True, help_text="Expanded school year, e.g. '2026-2027'.", max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='term_label',
            field=models.CharField(blank=True, db_index=True, help_text="Term as '<yy>-<sem>', e.g. '26-1'.", max_length=20),
        ),
    ]
