# Generated by Django 5.2.15 on 2026-09-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_stamp_existing_staff_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantrecord',
            name='linked_student',
            field=models.ForeignKey(blank=True, help_text='The portal account this record belongs to, where the person named on it has one. A dependent filed by an employee is matched to it by student number and date of birth.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_records', to='api.studentprofile'),
        ),
    ]
