from django.urls import path
from . import views
from . import student_views

urlpatterns = [
    # Public landing & apply routes
    path('', student_views.landing_view),
    path('apply/register/', student_views.apply_register_view),
    path('apply/login/', student_views.apply_login_view),
    path('apply/portal/', student_views.apply_portal_view),
    path('apply/submit/', student_views.apply_submit_view),
    path('apply/logout/', student_views.apply_logout_view),
    path('apply/result/', student_views.apply_result_view),
    path('apply/submitted/', student_views.apply_submitted_view),

    # Auth
    path('login/', student_views.login_view),
    path('logout/', student_views.logout_view),
    path('register/', student_views.register_view),

    # Academic student pages only
    path('student/', student_views.student_dashboard),
    path('student/apply/academic/', student_views.student_apply_academic),
    path('student/applications/', student_views.student_applications),
    path('student/notifications/', student_views.student_notifications),
    path('student/renewal/academic/', student_views.student_renewal_academic),
    path('student/link-scholarship/', student_views.student_link_scholarship),

    # REST API
    path('api/auth/register/', views.RegisterView.as_view()),
    path('api/auth/login/', views.LoginView.as_view()),
    path('api/auth/logout/', views.LogoutView.as_view()),
    path('api/student/profile/', views.StudentProfileView.as_view()),
    path('api/student/dashboard/', views.StudentDashboardView.as_view()),
    path('api/student/scholarships/', views.ScholarshipListView.as_view()),
    path('api/student/applications/', views.StudentApplicationListCreateView.as_view()),
    path('api/student/applications/<int:pk>/', views.StudentApplicationDetailView.as_view()),
    path('api/student/notifications/', views.NotificationListView.as_view()),
    path('api/student/announcements/', views.StudentAnnouncementListView.as_view()),
    path('api/vpsea/dashboard/', views.VPSEADashboardView.as_view()),
    path('api/vpsea/applications/', views.VPSEAApplicationListView.as_view()),
    path('api/vpsea/applications/<int:pk>/', views.VPSEAApplicationDetailView.as_view()),
    path('api/vpsea/renewals/', views.VPSEARenewalListView.as_view()),
    path('api/vpsea/renewals/<int:pk>/', views.VPSEARenewalDetailView.as_view()),
    path('api/vpsea/archives/<str:type>/', views.VPSEAArchiveListView.as_view()),
    path('api/vpsea/archives/<str:type>/upload/', views.VPSEAArchiveUploadView.as_view()),
    path('api/vpsea/analytics/', views.VPSEAAnalyticsView.as_view()),
    path('api/vpsea/announcements/', views.VPSEAAnnouncementListCreateView.as_view()),
    path('api/vpsea/reports/', views.VPSEAReportsView.as_view()),
    path('api/vpsea/ranking/', views.VPSEAStudentRankingView.as_view()),
    # VPSEA portal pages
    path('vpsea/', student_views.vpsea_dashboard),
    path('vpsea/affirmative/', student_views.vpsea_affirmative_applications),
    path('vpsea/applications/', student_views.vpsea_applications),
    path('vpsea/renewals/', student_views.vpsea_renewals),
    path('vpsea/archives/', student_views.vpsea_archives),
    path('vpsea/archives/add/', student_views.vpsea_archive_add),
    path('vpsea/archives/rollover/<int:pk>/delete/', student_views.vpsea_rollover_delete),
    path('vpsea/archives/import/', student_views.vpsea_archive_import),
    path('vpsea/archives/new-semester/', student_views.vpsea_new_semester),
    path('vpsea/archives/download/', student_views.vpsea_archive_download),
    path('vpsea/archives/<int:pk>/edit/', student_views.vpsea_archive_edit),
    path('vpsea/archives/<int:pk>/delete/', student_views.vpsea_archive_delete),
    path('vpsea/analytics/', student_views.vpsea_analytics),
    path('vpsea/announcements/', student_views.vpsea_announcements),
    path('vpsea/reports/', student_views.vpsea_reports),
    path('vpsea/reports/download/', student_views.vpsea_report_download),
    path('vpsea/reports/download/excel/', student_views.vpsea_report_download_excel),
    path('vpsea/scholarships/', student_views.vpsea_scholarships),
    path('vpsea/scholarships/add/', student_views.vpsea_scholarship_add),
    path('vpsea/scholarships/<int:pk>/edit/', student_views.vpsea_scholarship_edit),
    path('vpsea/scholarships/<int:pk>/toggle/', student_views.vpsea_scholarship_toggle),
    path('vpsea/ranking/', student_views.vpsea_ranking),
    path('vpsea/students/', student_views.vpsea_students),
    path('vpsea/students/add/', student_views.vpsea_student_add),
    path('vpsea/students/<int:pk>/edit/', student_views.vpsea_student_edit),
    path('vpsea/students/<int:pk>/delete/', student_views.vpsea_student_delete),
    # UniFAST portal pages
    path('unifast/', student_views.unifast_dashboard),
    path('unifast/tdp/', student_views.unifast_tdp),
    path('unifast/tes/', student_views.unifast_tes),
    path('unifast/continuing/', student_views.unifast_continuing),
    path('unifast/scholarships/', student_views.unifast_scholarships),
    path('unifast/scholarships/rollover/', student_views.unifast_scholarship_rollover),
    path('unifast/reports/', student_views.unifast_reports),
    path('api/unifast/dashboard/', views.UniFASTDashboardView.as_view()),
    path('api/unifast/tdp/', views.UniFASTTDPListView.as_view()),
    path('api/unifast/tdp/<int:pk>/', views.UniFASTTDPDetailView.as_view()),
    path('api/unifast/tes/', views.UniFASTTESView.as_view()),
    path('api/unifast/continuing/', views.UniFASTContinuingView.as_view()),
    path('api/unifast/billing/', views.UniFASTBillingListView.as_view()),
    path('api/unifast/distribution/', views.UniFASTDistributionView.as_view()),
    path('api/unifast/liquidation/', views.UniFASTLiquidationListView.as_view()),
    path('api/unifast/fhe/', views.UniFASTFHEView.as_view()),
    path('api/unifast/fhe/upload/', views.UniFASTFHEUploadView.as_view()),
    path('api/unifast/analytics/', views.UniFASTAnalyticsView.as_view()),
    path('api/unifast/reports/', views.UniFASTReportsView.as_view()),
    path('api/super/dashboard/', views.SuperDashboardView.as_view()),
    path('api/super/users/', views.SuperUserListCreateView.as_view()),
    path('api/super/users/<int:pk>/', views.SuperUserDetailView.as_view()),
    path('api/super/offices/', views.SuperOfficeListView.as_view()),
    path('api/super/categories/', views.SuperCategoryListView.as_view()),
    path('api/super/announcements/', views.SuperAnnouncementListCreateView.as_view()),
    path('api/super/logs/', views.SuperLogsView.as_view()),
    path('api/super/settings/', views.SuperSettingsView.as_view()),
]
